export const SEARCH_TITLE = 'SEARCH_TITLE'
export const SEARCH_YEAR = 'SEARCH_YEAR'
export const IMDBID_LIST = 'IMDBID_LIST'
export const INDEXOF_DETAILED_MOVIE = 'INDEXOF_DETAILED_MOVIE'
export const MOVIES_TABLE_DATA = "MOVIES_TABLE_DATA"
export const MOVIE_INFORMATIONS = "MOVIE_INFORMATIONS"
export const MODAL_SHOW="MODAL_SHOW"
export const REVIEWED_MOVIE_COUNTER="REVIEWED_MOVIE_COUNTER"